[platformio]
src_dir = ESP8266WirelessPrintAsync
default_envs = esp32dev

[env:esp32dev]
platform = platformio/espressif32@3.5.0
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_flags = -DLOG_LOCAL_LEVEL=ESP_LOG_NONE
lib_deps =
	https://github.com/me-no-dev/ESPAsyncWebServer#95dedf7
	https://github.com/ayushsharma82/AsyncElegantOTA#4b3528c
	https://github.com/alanswx/ESPAsyncWiFiManager#1c02154
	https://github.com/bblanchon/ArduinoJson#3df4efd
	https://github.com/bbx10/Hash_tng
	me-no-dev/AsyncTCP @ 1.1.1
