[platformio]
src_dir = ESP8266WirelessPrintAsync
default_envs = esp32dev

[env]
framework = arduino
lib_deps = 
	https://github.com/greiman/SdFat#3b79f38
	https://github.com/me-no-dev/ESPAsyncTCP#7e9ed22
	https://github.com/me-no-dev/ESPAsyncWebServer#95dedf7
	https://github.com/ayushsharma82/AsyncElegantOTA#4b3528c
	https://github.com/alanswx/ESPAsyncWiFiManager#1c02154
	https://github.com/bblanchon/ArduinoJson#3df4efd
build_flags = -DLOG_LOCAL_LEVEL=ESP_LOG_NONE

[base:esp32]
platform = platformio/espressif32@3.5.0
framework = ${env.framework}
lib_ignore = ESPAsyncTCP
lib_deps =
    ${env.lib_deps}
    https://github.com/bbx10/Hash_tng
    me-no-dev/AsyncTCP @ 1.1.1

[env:esp32dev]
board = esp32dev
extends = base:esp32
upload_speed = 115200
monitor_speed = 115200
